// var BASE_SERVER_URL =
// "http://hpcs01.comp.ae.keio.ac.jp:8080/wikipedia_ontology/";
var BASE_SERVER_URL = "http://hpcs01.comp.ae.keio.ac.jp/wikipedia_ontology/query/";
var BASE_URI = "http://www.yamaguti.comp.ae.keio.ac.jp/wikipedia_ontology/";

var BASE_CLASS_URI = BASE_URI + "class/";
var BASE_PROPERTY_URI = BASE_URI + "property/";
var BASE_INSTANCE_URI = BASE_URI + "instance/";

var BASE_SERVER_CLASS_URL = BASE_SERVER_URL + "class/";
var BASE_SERVER_CLASS_DATA_URL = BASE_SERVER_CLASS_URL + "data/";
var BASE_SERVER_CLASS_JSON_TABLE_URL = BASE_SERVER_CLASS_URL + "json_table/";
var BASE_SERVER_CLASS_JSON_TREE_URL = BASE_SERVER_CLASS_URL + "json_tree/";

var BASE_SERVER_PROPERTY_URL = BASE_SERVER_URL + "property/";
var BASE_SERVER_PROPERTY_DATA_URL = BASE_SERVER_PROPERTY_URL + "data/";
var BASE_SERVER_PROPERTY_JSON_TABLE_URL = BASE_SERVER_PROPERTY_URL
		+ "json_table/";
var BASE_SERVER_PROPERTY_JSON_TREE_URL = BASE_SERVER_PROPERTY_URL
		+ "json_tree/";

var BASE_SERVER_INSTANCE_URL = BASE_SERVER_URL + "instance/";
var BASE_SERVER_INSTANCE_DATA_URL = BASE_SERVER_INSTANCE_URL + "data/";
var BASE_SERVER_INSTANCE_JSON_TABLE_URL = BASE_SERVER_INSTANCE_URL
		+ "json_table/";
var BASE_SERVER_INSTANCE_JSON_TREE_URL = BASE_SERVER_INSTANCE_URL
		+ "json_tree/";

var JSON_TABLE_NULL_DATA = BASE_SERVER_CLASS_JSON_TABLE_URL + "NULL";
var JSON_TREE_NULL_DATA = BASE_SERVER_CLASS_JSON_TREE_URL + "NULL";
var JSON_TREE_ALL_CLASSES = BASE_SERVER_CLASS_JSON_TREE_URL + "ALLClasses.json";
