PREFIX++rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX++rdfs%3A++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX++wikiont_class%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Fclass%2F%3E%0APREFIX++wikiont_property%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Fproperty%2F%3E%0APREFIX++wikiont_instance%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Finstance%2F%3E%0A%0ASELECT+%3Finstance%0AWHERE%0A%7B%0A++++%3Finstance+rdf%3Atype+wikiont_class%3A%E9%9F%B3%E6%A5%BD%E5%AE%B6%3B%0A++++wikiont_property%3A%E5%87%BA%E8%BA%AB%E5%9C%B0+wikiont_instance%3A%E6%97%A5%E6%9C%AC.%0A%7D%0ALIMIT+1000%0A
