PREFIX++rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX++rdfs%3A++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX++wikiont_class%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Fclass%2F%3E%0APREFIX++wikiont_property%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Fproperty%2F%3E%0APREFIX++wikiont_instance%3A+%3Chttp%3A%2F%2Fwww.yamaguti.comp.ae.keio.ac.jp%2Fwikipedia_ontology%2Finstance%2F%3E%0A%0ASELECT+%3Finstance+%3Fclass%0AWHERE%0A%7B%0A++++%3Finstance+rdf%3Atype+%3Fclass%3B%0A++++wikiont_property%3A%E7%99%BA%E5%A3%B2%E5%85%83+wikiont_instance%3A%E4%BB%BB%E5%A4%A9%E5%A0%82%3B%0A++++wikiont_property%3A%E5%AF%BE%E5%BF%9C%E6%A9%9F%E7%A8%AE+wikiont_instance%3A%E3%83%8B%E3%83%B3%E3%83%86%E3%83%B3%E3%83%89%E3%83%BCDS%0A%7D%0ALIMIT+1000%0A
