PREFIX++rdf%3a+%3chttp%3a%2f%2fwww.w3.org%2f1999%2f02%2f22-rdf-syntax-ns%23%3e%0aPREFIX++rdfs%3a++%3chttp%3a%2f%2fwww.w3.org%2f2000%2f01%2frdf-schema%23%3e%0aPREFIX++wikiont_class%3a+%3chttp%3a%2f%2fwww.yamaguti.comp.ae.keio.ac.jp%2fwikipedia_ontology%2fclass%2f%3e%0aPREFIX++wikiont_property%3a+%3chttp%3a%2f%2fwww.yamaguti.comp.ae.keio.ac.jp%2fwikipedia_ontology%2fproperty%2f%3e%0aPREFIX++wikiont_instance%3a+%3chttp%3a%2f%2fwww.yamaguti.comp.ae.keio.ac.jp%2fwikipedia_ontology%2finstance%2f%3e%0a%0aSELECT+%3finstance+%3fclass%0aWHERE%0a%7b%0a++++%3finstance+rdf%3atype+%3fclass%3b%0a++++wikiont_property%3a%e7%99%ba%e5%a3%b2%e5%85%83+wikiont_instance%3a%e4%bb%bb%e5%a4%a9%e5%a0%82%3b%0a++++wikiont_property%3a%e5%af%be%e5%bf%9c%e6%a9%9f%e7%a8%ae+wikiont_instance%3a%e3%83%8b%e3%83%b3%e3%83%86%e3%83%b3%e3%83%89%e3%83%bcDS%0a%7d%0aLIMIT+1000